[versions]
kotlin = "2.3.0"
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"
graalvm-native = "0.11.3"
ktlint = "14.0.1"
node-gradle = "7.1.0"
htmx-spring-boot = "5.0.0"
cyclonedx = "3.1.0"
kover = "0.9.1"
jdbi = "3.51.0"
json-schema-validator = "3.0.0"

[libraries]
htmx-spring-boot-thymeleaf = { module = "io.github.wimdeblauwe:htmx-spring-boot-thymeleaf", version.ref = "htmx-spring-boot" }
jdbi-bom = { module = "org.jdbi:jdbi3-bom", version.ref = "jdbi" }
jdbi-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi" }
jdbi-kotlin = { module = "org.jdbi:jdbi3-kotlin", version.ref = "jdbi" }
jdbi-postgres = { module = "org.jdbi:jdbi3-postgres", version.ref = "jdbi" }
jdbi-jackson3 = { module = "org.jdbi:jdbi3-jackson3", version.ref = "jdbi" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
