[versions]
kotlin = "2.3.0"
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"
graalvm-native = "0.11.3"
ktlint = "14.0.1"
node-gradle = "7.1.0"
htmx-spring-boot = "5.0.0"

[libraries]
htmx-spring-boot-thymeleaf = { module = "io.github.wimdeblauwe:htmx-spring-boot-thymeleaf", version.ref = "htmx-spring-boot" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
